baseURL = "https://antehill.dev/"
languageCode = "en-us"
title = "ami@antehill:~$"
theme = "hugo-theme-shell"

# author = "Yukuro"
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

[Params]

# Additions start here
  [Params.Navbar]
  use = false
  
  [Params.Extensions]
  use = false
  ext = ".txt" # extension to add after single page
# Additions stop here
    
  # Note: This is for the meta description, which is different from the "description" displayed in the terminal.
  description = "Click to open a new terminal"
  [Params.Terminal]
  # Note: color scheme
  # Note: You can choose between
  # Note: hugo-theme-shell original: ["shell-powershell", "shell-ubuntu", "shell-retro"]
  # Note: gogh theme: https://mayccoll.github.io/Gogh/
  scheme = "Dracula"

  # Note: in terminal
  # [userName]@[pcName]:~/$ cd [workDir]
  # [userName]@[pcName]:~/[workDir]$ cat [profile]
  #
  # [description]
  #
  # Note: if you set Params.Tree > use = true
  # [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
  # ./[folderName]/
  # ...
  # Note: result of the tree command
  userName = "ami"
  pcName = "antehill"
  workDir = "antehill-site"
  profile = "about-admin.txt"

  # Note: speed at which text is displayed on the terminal
  # Note: if set to 0, typing animation will be disabled
  # Note:
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  ps1Delay = 15 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
  stdoutDelay = 15 # stdout speed : [description] , files in Params.Tree
  commandDelay = 15 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/

  # terminalDelay = 20 : deprecated

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  # Note: 
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  titleDelay = 20 # title speed : "title" in front matter
  contentDelay = 15 # content speed : content in .md file

  # activityDelay = 5 : deprecated

  # Note: If you want to use a Markdown file, you can use the following
  # description = "/description.md"
  # Note: and put the description.md in /content/description.md
description = """

      Hello, I'm Audrey Millana.
      People call me Ami.

      Just an artist with a computer.

      Join the discord for additional information on how to join our game servers.
      
    """

  [Params.Tree]
  use = true
  folderName = "antehill-resources"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [ 
    ["GitHub", "https://github.com/amillana"],
    ["Discord", "https://discord.gg/xNnDmKxv"],
  ]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.85.0"
